In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [17]:
import pandas as pd
from sklearn.linear_model import ElasticNet
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegressionCV
from sklearn.preprocessing import StandardScaler
# from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score,recall_score
import matplotlib.pyplot as plt
import numpy as np
from math import log, sqrt
%matplotlib inline 

In [18]:
credit_df = pd.read_csv("/content/drive/MyDrive/DataSets/creditcard.csv")

# Initial Analysis
##### Let's analyze this dataset to understand its characteristics

In [19]:
display(credit_df)

Time         V1         V2  ...       V28  Amount  Class
0            0.0  -1.359807  -0.072781  ... -0.021053  149.62      0
1            0.0   1.191857   0.266151  ...  0.014724    2.69      0
2            1.0  -1.358354  -1.340163  ... -0.059752  378.66      0
3            1.0  -0.966272  -0.185226  ...  0.061458  123.50      0
4            2.0  -1.158233   0.877737  ...  0.215153   69.99      0
...          ...        ...        ...  ...       ...     ...    ...
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[284807 rows x 31 columns]

In [20]:
#Let's round off values for easy interpretation
credit_df.describe().round(2)

Time         V1         V2  ...        V28     Amount      Class
count  284807.00  284807.00  284807.00  ...  284807.00  284807.00  284807.00
mean    94813.86       0.00       0.00  ...      -0.00      88.35       0.00
std     47488.15       1.96       1.65  ...       0.33     250.12       0.04
min         0.00     -56.41     -72.72  ...     -15.43       0.00       0.00
25%     54201.50      -0.92      -0.60  ...      -0.05       5.60       0.00
50%     84692.00       0.02       0.07  ...       0.01      22.00       0.00
75%    139320.50       1.32       0.80  ...       0.08      77.16       0.00
max    172792.00       2.45      22.06  ...      33.85   25691.16       1.00

[8 rows x 31 columns]

# Class Imbalance
### Notice the ratio of fraudulent to non-fraudulent transaction

In [21]:
credit_df["Class"].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [22]:
credit_df["Class"].value_counts(normalize=True)

0    0.998273
1    0.001727
Name: Class, dtype: float64

### Class is biased. 

There are significantly higher number of data points for class label 0 than label 1. This bias will lead to poor quality training for the model

To resolve this , we will use the technique of random undersampling. This will ensure we have equal number of data samples from each label to train the model

In [23]:
xy_array = credit_df.values #store the array values in an array
#start by scaling all the values

from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

credit_df['scaled_amount'] = std_scaler.fit_transform(credit_df['Amount'].values.reshape(-1,1))
credit_df['scaled_time'] = std_scaler.fit_transform(credit_df['Time'].values.reshape(-1,1))

credit_df.drop(['Time','Amount'], axis=1, inplace=True)



scaled_amount = credit_df['scaled_amount']
scaled_time = credit_df['scaled_time']

credit_df.drop(['scaled_amount', 'scaled_time'], axis=1, inplace=True)
credit_df.insert(0, 'scaled_amount', scaled_amount)
credit_df.insert(1, 'scaled_time', scaled_time)

# Amount and Time are Scaled!

credit_df.head()


scaled_amount  scaled_time        V1  ...       V27       V28  Class
0       0.244964    -1.996583 -1.359807  ...  0.133558 -0.021053      0
1      -0.342475    -1.996583  1.191857  ... -0.008983  0.014724      0
2       1.160686    -1.996562 -1.358354  ... -0.055353 -0.059752      0
3       0.140534    -1.996562 -0.966272  ...  0.062723  0.061458      0
4      -0.073403    -1.996541 -1.158233  ...  0.219422  0.215153      0

[5 rows x 31 columns]

# Random Undersampling
To resolve class imbalance , we will use the technique of random undersampling. This will ensure we have equal number of data samples from each label to train the model


# Steps to do undersampling based modeling

###1) Preserve the original values

###2) Scale all values if necessary

###3) If minority class values are too less, you'll have to do cross validation. Make sure you are also performing stratified sampling to maintain the original ratio of minority to majority classes.
###4) Divide original data into training and testing set. Verify if split is stratified
###5)  Now , sample the datset to ensure samples from all classes are equal in number
###6) Train the model on undersampled data
###7) Test the model on original values

In [24]:
from sklearn.model_selection import train_test_split

#Separate features and labels
X = credit_df.drop('Class', axis=1)
y = credit_df['Class']
original_Xtrain, original_Xtest, original_ytrain, original_ytest = train_test_split(X,y,stratify=y)

original_Xtrain = original_Xtrain.values
original_Xtest = original_Xtest.values
original_ytrain = original_ytrain.values
original_ytest = original_ytest.values

# See if both the train and test label distribution are similarly distributed
train_unique_label, train_counts_label = np.unique(original_ytrain, return_counts=True)
test_unique_label, test_counts_label = np.unique(original_ytest, return_counts=True)
print('-' * 100)

print('Label Distributions: \n')
print(train_counts_label/ len(original_ytrain))
print(test_counts_label/ len(original_ytest))

----------------------------------------------------------------------------------------------------
Label Distributions: 

[0.99827251 0.00172749]
[0.99827252 0.00172748]


In [25]:
# Since our classes are highly skewed we should make them equivalent in order to have a normal distribution of the classes.

# Lets shuffle the data before creating the subsamples

credit_df = credit_df.sample(frac=1)

# amount of fraud classes 492 rows.
fraud_credit_df = credit_df.loc[credit_df['Class'] == 1]
non_fraud_credit_df = credit_df.loc[credit_df['Class'] == 0][:492]

normal_distributed_credit_df = pd.concat([fraud_credit_df, non_fraud_credit_df])

# Shuffle dataframe rows
new_credit_df = normal_distributed_credit_df.sample(frac=1, random_state=42)

new_credit_df.head()

scaled_amount  scaled_time         V1  ...       V27       V28  Class
176975      -0.193346     0.593268  -0.770044  ...  0.219622  0.238264      0
252124      -0.350151     1.281336  -1.928613  ...  0.573393  0.294686      1
274493       0.646292     1.499917   1.450032  ...  0.014090 -0.004410      0
154676      -0.344114     0.162739  -1.456876  ...  0.318152 -0.323554      1
153823      -0.344114     0.113905 -19.641857  ... -4.126746 -0.645329      1

[5 rows x 31 columns]

In [26]:
from sklearn.model_selection import train_test_split


X = new_credit_df.drop('Class', axis=1)
y = new_credit_df['Class']
# This is explicitly used for undersampling.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:

#now we're ready to train.  
clf = LogisticRegressionCV(max_iter=10000,cv=5, penalty='elasticnet',  l1_ratios=[0.1, 0.5, 1.0],
                           solver='saga',
                           random_state=0).fit(X_train, y_train)

In [28]:
print('accuracy on training data = ', clf.score(X_train, y_train))


print('accuracy on test data = ', clf.score(original_Xtest, original_ytest))
      

accuracy on training data =  0.9440914866581956
accuracy on test data =  0.9788067750905873


##  
##  Confusion matrix

The definition a confusion matrix is such that Cij is equal to the number of observations known to be in group i and predicted to be in group j.

That means that entries in the confusion matrix C00, C10, C01, C11 represent the following values:
- C00 = true negatives
- C10 = false negatives
- C11 = true positives
- C01 = false positives


# Experiment with threshold values to get best TP and FP numbers


In [29]:
#Generally metrics require probability predictions.  
probs_te = clf.predict_proba(original_Xtest)
prob1 = [x[1] for x in probs_te] #linear model returns prob of both binary outcomes

#threshold at 0.5
y_te_05 = [int(x + 0.5) for x in prob1]
y_te_75 = [int(x + 0.25) for x in prob1]
y_te_25 = [int(x + 0.75) for x in prob1]

conf_mat05 = confusion_matrix(original_ytest, y_te_05)
conf_mat75 = confusion_matrix(original_ytest, y_te_75)
conf_mat25 = confusion_matrix(original_ytest, y_te_25)

print('confusion matrix with 0.5 threshold \n', conf_mat05)
print('confusion matrix with 0.75 threshold \n', conf_mat75)
print('confusion matrix with 0.25 threshold \n', conf_mat25)

confusion matrix with 0.5 threshold 
 [[69580  1499]
 [   10   113]]
confusion matrix with 0.75 threshold 
 [[70344   735]
 [   14   109]]
confusion matrix with 0.25 threshold 
 [[65066  6013]
 [    6   117]]


##  
##  Feature Importance

For penalized linear regression, we'll use the coefficient magnitudes to indicate the value of the corresponding features.  Those are available as an output from the training process.  In order of importance here are the most important features (remember that it's that absolute value of the coefficient that counts).

1. ca       -0.789812
2. cp        0.708058
3. thalach   0.581009
4. old peak -0.575971
5. thal     -0.462587


In [30]:
coef = clf.coef_
coef=np.array([abs(xi) for xi in coef])
columns = new_credit_df.columns[0:30]
plm_importance_df = pd.DataFrame.from_dict(dict(zip(columns, coef)), orient='index', columns=columns)
display(plm_importance_df.T.sort_values(by='scaled_amount',ascending=False).head(20))

scaled_amount
V4                  0.632758
V14                 0.575927
V12                 0.279500
V10                 0.267236
V8                  0.229798
V23                 0.194319
V3                  0.189483
scaled_amount       0.186835
V11                 0.155163
V19                 0.128150
V13                 0.123534
scaled_time         0.120809
V22                 0.057860
V9                  0.050819
V25                 0.048682
V5                  0.047673
V1                  0.043299
V26                 0.041158
V16                 0.026470
V21                 0.023035